name: _terraform-docs

on:
  pull_request:
    paths:
      - 'terraform/modules/**'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  terraform-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1, released 2025-12, checked 2026-01
        with:
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref_name }}
      - uses: ulfiac/common-reusables/.github/actions/dump_context@main
      - uses: terraform-docs/gh-actions@6de6da0cefcc6b4b7a5cbea4d79d97060733093c # v1.4.1, released 2025-05, checked 2026-01
        with:
          args: --anchor=false
          find-dir: terraform/modules
          git-push: true
          output-file: README.md
          output-method: inject
