name: deploy github
run-name: "${{ inputs.terragrunt_action }}: github, ${{ inputs.type }}, ${{ inputs.name }}"

on:
  workflow_dispatch:
    inputs:
      type:
        default: all
        options:
          - all
          - repo
        required: true
        type: choice
      name:
        default: all
        required: true
        type: string
      terragrunt_action:
        default: plan
        options:
          - plan
          - plan destroy
          - apply
          - destroy
        required: true
        type: choice
      annotate_apply_details:
        default: false
        required: false
        type: boolean
      annotate_context_details:
        default: false
        required: false
        type: boolean
      annotate_plan_details:
        default: false
        required: false
        type: boolean
      annotate_plan_summary:
        default: true
        required: false
        type: boolean
      terragrunt_parallelism:
        default: true
        required: false
        type: boolean

permissions:
  contents: read
  id-token: write

jobs:
  deploy-github:
    name: ${{ inputs.name == 'all' && format('github/{0}', matrix.type) || format('github/{0}/{1}', matrix.type, inputs.name) }}
    strategy:
      matrix:
        type: ${{ fromJson(inputs.type == 'all' && '["repo"]' || format('["{0}"]', inputs.type)) }}
    uses: ./.github/workflows/reusable_terragrunt_action.yaml
    with:
      annotate_apply_details: ${{ inputs.annotate_apply_details }}
      annotate_context_details: ${{ inputs.annotate_context_details }}
      annotate_plan_details: ${{ inputs.annotate_plan_details }}
      annotate_plan_summary: ${{ inputs.annotate_plan_summary }}
      aws_region: us-east-2
      github_environment: github
      terragrunt_action: ${{ inputs.terragrunt_action }}
      terragrunt_all: ${{ inputs.name == 'all' && true || false }}
      terragrunt_parallelism: ${{ inputs.terragrunt_parallelism }}
      working_dir: ${{ inputs.name == 'all' && format('github/{0}', matrix.type) || format('github/{0}/{1}', matrix.type, inputs.name) }}
    secrets: inherit
