name: deploy earn credits layer
run-name: deploy earn credits layer - ${{ github.event.inputs.terraform_action }}

on:
  workflow_dispatch:
    inputs:
      terraform_action:
        default: destroy
        description: terraform action
        options:
          - plan
          - plan destroy
          - apply
          - destroy
        required: true
        type: choice

permissions:
  contents: read
  id-token: write

jobs:
  deploy-earn-credits-layer:
    uses: ./.github/workflows/reusable_deploy.yaml
    with:
      auth: oidc
      aws_region: us-east-1
      terraform_action: ${{ github.event.inputs.terraform_action }}
      terraform_layer: earn_credits_layer
    secrets: inherit
