name: linter
run-name: "linter: ${{ github.event_name == 'pull_request' && github.event.pull_request.title || github.ref_name }}"

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  reusable-linter:
    uses: ulfiac/github-action-reusables/.github/workflows/reusable_linter.yaml@main
    with:
      shellcheck-scandir: "./scripts"
      terraform-fmt-path: "./terraform"
