name: _purge

on:
  schedule:
    - cron: '53 10 * * *' # run daily at midnight UTC
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  purge-logs:
    uses: ulfiac/github-action-reusables/.github/workflows/reusable_purge_workflow_logs.yaml@main
    with:
      retain-days: 7
